[project]
name = "talk-slides"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eurostat>=1.1.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
]
